description: Simple PyTorch job on MNIST on AMLK8s

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  name: itpseasiav100cl
  vc: resrchvc

environment:
  image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
  registry: docker.io # any public registry can be specified here
  setup:
    - pip install tensorboard --user

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/src

# data:
#   data upload is not required for this example

# list of jobs to run, we run 2 jobs in this example
jobs:
- name: high_lr
  sku: G1
  command:
  - python main.py --lr 0.5
- name: low_lr
  sku: G1
  command:
  - python main.py --lr 0.1
