description: Simple PyTorch job on MNIST

environment:
  image: pytorch/pytorch:1.5-cuda10.1-cudnn7-devel
  setup:
    - pip install tensorboard

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/src

# data:
#   data upload is not required for this example

# list of jobs to run, we run 2 jobs in this example
jobs:
  # name must be unique across the jobs
- name: high_lr
  # one gpu
  sku: G1
  command:
  - python main.py --lr 0.5
- name: low_lr
  # one gpu
  sku: G1
  command:
  - python main.py --lr 0.1