description: roberta_phone_pretrain

# AML
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
  # cluster_group: MS-Shared


environment:
  image: wumark/speech_transducer:torch1.6_wav2vec
  setup:
    - bash submit_script/ITP_bash_scripts/data2vec/data2vec_audio_conda.sh

# azure blob configuration
storage:
  data_blob:
    storage_account_name: tsprmblob01scus
    container_name: data
    mount_dir: /datablob
    mount_options:
    - -o
    - attr_timeout=240
    - -o
    - entry_timeout=240
    - -o
    - negative_timeout=120
    - -o
    - allow_other
    - --log-level=LOG_WARNING
    - --file-cache-timeout-in-seconds=3600
  #info:
  #  output:
  #    container_name: teamdrive
  #    storage_account_name: msranlcmtteamdrive
  #    mount_dir: /datablob/users
  #    is_output: true

# code dir
code:
  local_dir: ~/github/fairseq/

# job configuration
jobs:
  - name: roberta_phone_pretrain
    sku: G8
    command:
      - bash submit_script/ITP_bash_scripts/roberta/roberta_phone_pretrain.sh
