description: Distributed Pytorch MNIST examples

environment:
  image: horovod/horovod:0.19.1-tf2.1.0-torch1.4.0-mxnet1.6.0-py3.6-gpu
  setup:
  - pip install pytorch-lightning==1.5.0 --user

code:
  local_dir: $CONFIG_DIR/src

jobs:
- name: one_node
  sku: 1xG8
  # disables mpi and just returns one node
  aml_mpirun:
    process_count_per_node: 0
  command:
  - echo "No process"
- name: one_process_per_node
  sku: 1xG8
  # enables mpi and spawns one process per node
  aml_mpirun:
    process_count_per_node: 1
  command:
  - echo "One process per node"
