description: data2vec_uni_pretrain_100h_860h_textDoEma_releasedSpeechModel_190w_G8

# AML
target:
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc
  # cluster_group: MS-Shared

environment:
  # image: wumark/speech_transducer:a100_fairseq_kenlm
  image: sanyuanchen/data2vec:torch1.8
  # image: wumark/speech_transducer:torch1.6_wav2vec
  # image: pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
  # registry: docker.io # any public registry can be specified here
  setup:
    - pip install --editable ./
  #   - ./submit_script/ITP_bash_scripts/data2vec/install.sh

# azure blob configuration
storage:
  data_blob:
    storage_account_name: tsprmblob01scus
    container_name: data
    mount_dir: /datablob
    mount_options:
    - -o
    - attr_timeout=240
    - -o
    - entry_timeout=240
    - -o
    - negative_timeout=120
    - -o
    - allow_other
    - --log-level=LOG_WARNING
    - --file-cache-timeout-in-seconds=3600
  # blob_model:
  #   storage_account_name: tsstd01wus2
  #   container_name: models
  #   mount_dir: /modelblob

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ~/github/fairseq/

# list of jobs to run
jobs:
- name: data2vec_uni_pretrain_100h_860h_textDoEma_releasedSpeechModel_190w_G8
  sku: G8
  # sku_count: 1 #deprecated
  # aml_mpirun:
    # process_count_per_node: 4
    # communicator: "OpenMpi"
  command:
    # - bash submit_script/debug/debug.sh
    - bash data2vec_uni/submit_pretrain_releasedSpeechModel.sh
    - sleep infinity