description: data2vec_960h_repreduce

target:
  name: msrresrchvc
  service: aisc
  research_group: gcr-singularity-resrch

environment:
  image: sanyuanchen/data2vec:torch1.8
  setup:
    - pip install --editable ./

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: ~/github/fairseq/

storage:
  data_blob:
    storage_account_name: tsprmblob01scus
    container_name: data
    mount_dir: /datablob
    mount_options:
    - -o
    - attr_timeout=240
    - -o
    - entry_timeout=240
    - -o
    - negative_timeout=120
    - -o
    - allow_other
    - --log-level=LOG_WARNING
    - --file-cache-timeout-in-seconds=3600

jobs:
- aml_mpirun:
    communicator: OpenMpi
  name: data2vec_960h_repreduce
  sku: 2xG8
  submit_args:
    constraints:
    - tag: connectivityDomain
      type: uniqueConstraint
    env:
      HOROVOD_HIERARCHICAL_ALLREDUCE: 1
      MKL_THREADING_LAYER: GNU
      NCCL_ASYNC_ERROR_HANDLING: 1
      NCCL_DEBUG: INFO
      NCCL_IB_DISABLE: 0
      NCCL_IB_TIMEOUT: 22
  command:
  - bash submit_script/ITP_bash_scripts/data2vec/data2vec_audio_pretraining_reproduce.sh
  - sleep infinity